pool:
  vmImage: 'ubuntu-latest'

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'
    architecture: 'x64'

- bash: |
    apt-get update -qqy
    apt-get -qqy --no-install-recommends install firefox
    rm -rf /var/lib/apt/lists/* /var/cache/apt/*
    wget --no-verbose -O /tmp/firefox.tar.bz2 $(FIREFOX_DOWNLOAD_URL)
    apt-get -y purge firefox
    rm -rf /opt/firefox
    tar -C /opt -xjf /tmp/firefox.tar.bz2
    rm /tmp/firefox.tar.bz2
    mv /opt/firefox /opt/firefox-$(FIREFOX_VERSION)
    ln -fs /opt/firefox-$(FIREFOX_VERSION)/firefox /usr/bin/firefox
  displayName: 'Install Firefox'

- bash: |
    wget --no-verbose -O /tmp/geckodriver.tar.gz $(GD_DOWNLOAD_URL)
    rm -rf /opt/geckodriver
    tar -C /opt -zxf /tmp/geckodriver.tar.gz
    rm /tmp/geckodriver.tar.gz
    mv /opt/geckodriver /opt/geckodriver-$(GD_VERSION)
    chmod 755 /opt/geckodriver-$(GD_VERSION)
    ln -fs /opt/geckodriver-$(GD_VERSION) /usr/bin/geckodriver
  displayName: 'Install GeckoDriver'

- bash: python -m pip install --upgrade pip setuptools wheel
  displayName: 'Install PIP and SetupTools'

- bash: pip install -r requirements.txt
  displayName: 'Install Behave Requirements'

- bash: python -m behave --junit
  displayName: 'Behave Tests'

- task: CopyFiles@2
  displayName: 'Copy Screenshots'
  inputs:
    contents: '*.png'
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: CopyFiles@2
  displayName: 'Copy Logs'
  inputs:
    contents: '*.log'
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: '$(Build.BuildId).DebugBuilds'
    publishLocation: 'Container'